M48
; DRILL file {KiCad 9.0.6} date 2025-11-24T17:06:34-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-24T17:06:34-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.300
%
G90
G05
T1
X100.94Y-68.072
X100.94Y-135.382
X198.73Y-68.072
X198.73Y-135.382
M30
